version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  db:
    networks:
      - internal
    labels:
      - traefik.enable=false
  server:
    labels:
      - traefik.backend=ucn-api
      - traefik.frontend.rule=Host:ucn.juandastic.co
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy
  phpmyadmin:
    environment:
      PMA_ABSOLUTE_URI: https://ucn.juandastic.co/db_admin/
    labels:
      - traefik.backend=ucn-dbadmin
      - traefik.frontend.rule=Host:ucn.juandastic.co;PathPrefixStrip:/db_admin
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
