version: "3"

services:
  db:
    image: mysql:5.7
    volumes:
       - ./database/db_data:/var/lib/mysql
       - ./database/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ucnlogin
  server:
    build: ./api/
    environment:
      DATABASE_HOST: db
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ucnlogin
volumes:
  db_data: